#!/usr/bin/env zsh

zmodload zsh/datetime 2>/dev/null

_zshx_load() {
  local modules_dir="$HOME/.config/zshx/zshx.d"
  local -a skip_list only_list
  skip_list=(${(s:,:)ZSHX_SKIP})
  only_list=(${(s:,:)ZSHX_ONLY})

  local module name short
  for module in "$modules_dir"/*(N.); do
    name=${module:t}
    short=${name#<->-}

    if (( ${#only_list} )) && (( ! ${only_list[(Ie)$short]} )); then
      continue
    fi
    if (( ${skip_list[(Ie)$short]} )); then
      continue
    fi

    if [[ -n $ZSHX_PROFILE ]]; then
      local t0=$EPOCHREALTIME
      source "$module" || print -ru2 "zshx: failed to source $name"
      local t1=$EPOCHREALTIME
      printf 'zshx: %-20s %6.2fms\n' "$short" "$(( (t1-t0)*1000 ))"
    else
      source "$module" || print -ru2 "zshx: failed to source $name"
    fi
  done
}

_zshx_load
unset -f _zshx_load
